channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=24.0
- pip:
  - mlflow==2.4
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - psutil==6.0.0
  - scikit-learn==1.2.2
  - scipy==1.13.1
name: mlflow-env
